require('tap-browser-color')()
/*
require('../clear')
require('../triangle')
require('../line')
require('../batch')
require('../caps')
require('../depth')
require('../elements')
require('../draw')
require('../blend')
*/
require('../stencil')
/*
require('../viewport')
require('../misc')
*/
